version: "3"

services:
  frontend:
    image: node:current-alpine
    container_name: frontend
    network_mode: "host"
    volumes:
      - ./client:/frontend
    working_dir: /frontend
    entrypoint: ./start.sh 

  database:
    image: postgres:14-alpine
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=hackaton
      - POSTGRES_PASSWORD=password

